version: "3.7"
networks:
  redpanda_network:
    driver: bridge
volumes:
  redpanda-3: null
  redpanda-4: null
services:
  redpanda-3:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:49092
      # Address the broker advertises to clients that connect to the Kafka API.
      # Use the internal addresses to connect to the Redpanda brokers'
      # from inside the same Docker network.
      # Use the external addresses to connect to the Redpanda brokers'
      # from outside the Docker network.
      - --advertise-kafka-addr internal://redpanda-0:9092,external://localhost:49092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:48082
      # Address the broker advertises to clients that connect to the HTTP Proxy.
      - --advertise-pandaproxy-addr internal://redpanda-0:8082,external://localhost:48082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:48081
      # Redpanda brokers use the RPC API to communicate with each other internally.
      - --rpc-addr redpanda-3:33145
      - --advertise-rpc-addr redpanda-3:33145
      # Mode dev-container uses well-known configuration properties for development in containers.
      - --mode dev-container
      # Tells Seastar (the framework Redpanda uses under the hood) to use 1 core on the system.
      - --smp 1
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.10
    container_name: redpanda-3
    volumes:
      - redpanda-3:/var/lib/redpanda/data
    networks:
      - redpanda_network
    ports:
      - 48081:18081
      - 48082:18082
      - 49092:19092
      - 49644:9644
  redpanda-4:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:59092
      - --advertise-kafka-addr internal://redpanda-1:9092,external://localhost:59092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:58082
      - --advertise-pandaproxy-addr internal://redpanda-1:8082,external://localhost:58082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:58081
      - --rpc-addr redpanda-4:33145
      - --advertise-rpc-addr redpanda-4:33145
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.10
    container_name: redpanda-4
    volumes:
      - redpanda-4:/var/lib/redpanda/data
    networks:
      - redpanda_network
    ports:
      - 58081:58081
      - 58082:58082
      - 59092:59092
      - 59644:9644
  