{
 "title": "Redpanda",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Cluster-level metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redpanda_cluster_brokers", "legendFormat": "Nodes Up" }
   ]
  },
  {
   "title": "Partitions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group(redpanda_kafka_max_offset{redpanda_topic!~\"id_allocator|controller|__consumer_offsets\"}) by (redpanda_namespace, redpanda_topic, redpanda_partition)) by (redpanda_namespace)",
     "legendFormat": "Partition count"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(group(redpanda_kafka_max_offset{redpanda_topic!~\"id_allocator|controller|__consumer_offsets\"}) by (redpanda_namespace, redpanda_topic)) by (redpanda_topic))",
     "legendFormat": "Partition count"
    }
   ]
  },
  {
   "title": "Unavailable Partitions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redpanda_cluster_unavailable_partitions",
     "legendFormat": "Partition count"
    }
   ]
  },
  {
   "title": "Under-replicated Partitions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redpanda_kafka_under_replicated_replicas) by (redpanda_topic) > 0",
     "legendFormat": "Partition count"
    }
   ]
  },
  { "title": "Consumer Groups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Consumer Group Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by(redpanda_group, redpanda_topic)(redpanda_kafka_max_offset) - on(redpanda_topic, redpanda_partition) group_right max by(redpanda_group, redpanda_topic)(redpanda_kafka_consumer_group_committed_offset)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumers per Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(redpanda_group)(redpanda_kafka_consumer_group_consumers)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumer Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(redpanda_kafka_request_bytes_total{redpanda_request=\"consume\",redpanda_topic!~\"id_allocator|controller\"} [5m] )) by (redpanda_topic)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Producer Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(redpanda_kafka_request_bytes_total{redpanda_request=\"produce\",redpanda_topic!~\"id_allocator|controller\"} [5m] )) by (redpanda_topic)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Consumer Request Latency (p95)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(redpanda_kafka_request_latency_seconds_bucket{redpanda_request=\"consume\"}[5m])) by (le, provider, region, instance, namespace, pod))",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Kafka Producer Request Latency (p95)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(redpanda_kafka_request_latency_seconds_bucket{redpanda_request=\"produce\"}[5m])) by (le, provider, region, instance, namespace, pod))",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Infrastructure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "1- (sum(redpanda_storage_disk_free_bytes) by (instance)) / (sum(redpanda_storage_disk_total_bytes) by (instance))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Free Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(redpanda_memory_free_memory) by (instance) ",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}