version: '3.7'
networks:
  redpanda_network:
    driver: bridge
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
      - "GF_AUTH_ANONYMOUS_HIDE_VERSION=true"
    volumes:
      - "./grafana-config/provisioning:/etc/grafana/provisioning"
      - "./grafana-config/dashboards:/var/lib/grafana/dashboards"
    ports: [ "3000:3000" ]
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes: [ "./prometheus-config:/etc/prometheus" ]
    ports: 
      - "9090:9090"


