apiVersion: redpanda.vectorized.io/v1alpha1
kind: Cluster
metadata:
  name: redpanda-cluster
spec:
  image: {{ .Values.redpanda.image }}
  version: {{ .Values.redpanda.version }}
  replicas: {{ .Values.brokers.count }}
  storage: 
    capacity: {{ .Values.resources.storage.capacity }}
  {{- if .Values.sasl.enabled }}
  enableSasl: true
  superUsers:
    - username: admin
  {{- end }}
  resources:
    requests:
      cpu: {{ .Values.resources.cpu.request }}
      memory: {{ .Values.resources.memory.request }}
    limits:
      cpu: {{ .Values.resources.cpu.limit }}
      memory: {{ .Values.resources.memory.limit }}
  configuration:
    rpcServer:
      port: 33145
    kafkaApi:
    - port: 9092
      {{- if .Values.tls.enabled }}
      tls:
        enabled: true
        requireClientAuth: true
      {{- end }}
    pandaproxyApi:
    - port: 8082
      {{- if .Values.tls.enabled }}
      tls:
        enabled: true
        requireClientAuth: true
      {{- end }}
    schemaRegistry:
      port: 8081
      {{- if .Values.tls.enabled }}
      tls:
        enabled: true
        requireClientAuth: true
      {{- end }}
    adminApi:
    - port: 9644
      {{- if .Values.tls.enabled }}
      tls:
        enabled: true
        requireClientAuth: true
      {{- end }}
    developerMode: true
